some improvments

diff --git a/scripts/change-wall b/scripts/change-wall
--- a/scripts/change-wall
+++ b/scripts/change-wall
@@ -1,6 +1,16 @@
 #!/usr/bin/env bash
 
-IMG=$(imv -r ~/.dotfiles/walls/)
+fimg() {
+    cmd="find ~/.dotfiles/walls -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.gif' -o -iname '*.webp' \)"
+
+  preview_cmd="img2sixel -w 800 -q low {} 2>/dev/null || echo 'Preview failed'"
+
+  eval "$cmd" | fzf \
+    --preview="$preview_cmd" \
+    --preview-window="right:50%"
+}
+
+IMG=$(fimg)
 
 if [ -z "$IMG" ]; then
     exit 0
@@ -9,7 +19,7 @@ fi
 killall wbg &>/dev/null
 wbg "$IMG" &>/dev/null &
 sed -i \
-  -E "s|^(.*wbg) ~/.dotfiles/walls/[^/]+\.jpg( &.*)$|\1 $IMG\2|" \
-  ~/start
+    -E "s|^(wbg) /home/nnofly/.dotfiles/walls/[^/]+\.jpg( &.*)$|\1 $IMG\2|" \
+  ~/.dotfiles/scripts/start
 
 disown -a
